name: Deploy

on:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy

    steps:
      - uses: actions/checkout@master

      - name: Bucket actions
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - run: npm run build

      - name: Publish
        uses: appleboy/scp-action@master
        with:
          source: ./dist/*
          host: ${{ secrets.SSH_HOST }}
          target: ${{ secrets.SSH_DIR }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          strip_components: 1
          overwrite: true
